export namespace nodes {
    export { details };
    export { summary };
    export { summary_block };
    export { dl };
    export { dt };
    export { dd };
    export { fieldset };
    export { legend };
    export { picture };
    export { audio };
    export { video };
    export { track };
    export { source };
    export { object };
    export { figure };
    export { figcaption };
    export { small };
    export { ruby };
    export { rp };
    export { rt };
    export { iframe };
    export let table: import("prosemirror-model").NodeSpec;
    export let table_row: import("prosemirror-model").NodeSpec;
    export let table_cell: import("prosemirror-model").NodeSpec;
    export let table_header: import("prosemirror-model").NodeSpec;
    export { doc };
    export { text };
    export { paragraph };
    export { blockquote };
    export { secret };
    export { horizontal_rule };
    export { heading };
    export { code_block };
    export { imageLink as image_link };
    export { image };
    export { hard_break };
    export { ordered_list };
    export { bullet_list };
    export { list_item };
    export { list_item_text };
    export { table_complex };
    export { tbody };
    export { thead };
    export { tfoot };
    export { caption };
    export { caption_block };
    export { colgroup };
    export { col };
    export { table_row_complex };
    export { table_cell_complex };
    export { table_header_complex };
    export { table_cell_complex_block };
    export { table_header_complex_block };
}
export namespace marks {
    export { superscript };
    export { subscript };
    export { span };
    export { font };
    export { link };
    export { em };
    export { strong };
    export { underline };
    export { strikethrough };
    export { code };
}
export const schema: Schema<"object" | "small" | "track" | "source" | "secret" | "audio" | "blockquote" | "caption" | "col" | "colgroup" | "dd" | "details" | "dl" | "dt" | "fieldset" | "figcaption" | "figure" | "iframe" | "legend" | "picture" | "rp" | "rt" | "ruby" | "summary" | "table" | "tbody" | "tfoot" | "thead" | "video" | "image" | "text" | "doc" | "ordered_list" | "bullet_list" | "code_block" | "heading" | "horizontal_rule" | "hard_break" | "list_item" | "paragraph" | "table_row" | "table_cell" | "table_header" | "summary_block" | "image_link" | "list_item_text" | "table_complex" | "caption_block" | "table_row_complex" | "table_cell_complex" | "table_header_complex" | "table_cell_complex_block" | "table_header_complex_block", "link" | "code" | "font" | "em" | "span" | "strong" | "underline" | "strikethrough" | "superscript" | "subscript">;
import { details } from "./schema/other.mjs";
import { summary } from "./schema/other.mjs";
import { summaryBlock as summary_block } from "./schema/other.mjs";
import { dl } from "./schema/other.mjs";
import { dt } from "./schema/other.mjs";
import { dd } from "./schema/other.mjs";
import { fieldset } from "./schema/other.mjs";
import { legend } from "./schema/other.mjs";
import { picture } from "./schema/other.mjs";
import { audio } from "./schema/other.mjs";
import { video } from "./schema/other.mjs";
import { track } from "./schema/other.mjs";
import { source } from "./schema/other.mjs";
import { object } from "./schema/other.mjs";
import { figure } from "./schema/other.mjs";
import { figcaption } from "./schema/other.mjs";
import { small } from "./schema/other.mjs";
import { ruby } from "./schema/other.mjs";
import { rp } from "./schema/other.mjs";
import { rt } from "./schema/other.mjs";
import { iframe } from "./schema/other.mjs";
declare namespace doc {
    let content: string;
}
declare namespace text {
    let group: string;
}
import { paragraph } from "./schema/core.mjs";
import { blockquote } from "./schema/core.mjs";
declare const secret: any;
import { hr as horizontal_rule } from "./schema/core.mjs";
import { heading } from "./schema/core.mjs";
import { pre as code_block } from "./schema/core.mjs";
declare const imageLink: any;
declare const image: any;
import { br as hard_break } from "./schema/core.mjs";
import { ol as ordered_list } from "./schema/lists.mjs";
import { ul as bullet_list } from "./schema/lists.mjs";
import { li as list_item } from "./schema/lists.mjs";
import { liText as list_item_text } from "./schema/lists.mjs";
import { tableComplex as table_complex } from "./schema/tables.mjs";
import { tbody } from "./schema/tables.mjs";
import { thead } from "./schema/tables.mjs";
import { tfoot } from "./schema/tables.mjs";
import { caption } from "./schema/tables.mjs";
import { captionBlock as caption_block } from "./schema/tables.mjs";
import { colgroup } from "./schema/tables.mjs";
import { col } from "./schema/tables.mjs";
import { tableRowComplex as table_row_complex } from "./schema/tables.mjs";
import { tableCellComplex as table_cell_complex } from "./schema/tables.mjs";
import { tableHeaderComplex as table_header_complex } from "./schema/tables.mjs";
import { tableCellComplexBlock as table_cell_complex_block } from "./schema/tables.mjs";
import { tableHeaderComplexBlock as table_header_complex_block } from "./schema/tables.mjs";
import { superscript } from "./schema/marks.mjs";
import { subscript } from "./schema/marks.mjs";
import { span } from "./schema/marks.mjs";
import { font } from "./schema/marks.mjs";
declare const link: any;
import { em } from "./schema/marks.mjs";
import { strong } from "./schema/marks.mjs";
import { underline } from "./schema/marks.mjs";
import { strikethrough } from "./schema/marks.mjs";
import { code } from "./schema/marks.mjs";
import { Schema } from "prosemirror-model";
export {};
